### ISSUE TITLE
missing file "../chroma/dark.less" in sources

### ISSUE THREAD

**Issue by lafleurdeboum** [iamdoubz/Gitea-Pitch-Black#6]
Trying to compile the css from `theme-pitchblack.less` with clessc (a C++ less compiler) fails with the following error : 
```
theme-pitchblack.less: Line 0, Column 8 Parse Error: Found "../chroma/dark.less" when expecting existing file
```
(which is a funny way to put it, don't you think ?) Indeed, there is no such file in the sources.

Would you care to include it in the sources ? It would allow (eg me) to contribute MRs. Although this theme is really neat as is IMHO.

**Comment by iamdoubz** [comment]
Aww I see what you are doing here. My (initial) contribution was to put this file in the web_src location of Gitea itself, but never thought about compiling it separately...

"Chroma" can be found here: https://github.com/go-gitea/gitea/tree/main/web_src/less/chroma/dark.less

Also, thanks for using!

**Comment by lafleurdeboum** [comment]
Oh, so this repo is intended as a submodule for Gitea then ? Maybe would you care to add install instructions to `README.md`, or even a separate `INSTALL.md` ?

**Comment by iamdoubz** [comment]
Already ahead of you. In progress. Once it is done, I'll send an update and close this ticket perhaps?

**Comment by lafleurdeboum** [comment]
Sure. Looking forward !
