### ISSUE TITLE
Possibilty to override the code editor theme?

### ISSUE THREAD

**Issue by Thaodan** [iamdoubz/Gitea-Pitch-Black#7]
The theme uses the default editor theme which is hard to read with this theme.

**Comment by iamdoubz** [comment]
Could you please provide a screen shot of the exact area that is troubling to view? @Thaodan

**Comment by Thaodan** [comment]
Here you go:

**Comment by Thaodan** [comment]
<img width="908" alt="Screenshot_20220917_050659" src="https://user-images.githubusercontent.com/1747359/190836369-c5be6160-9ea9-4213-9cae-c1d30c68f259.png">

**Comment by iamdoubz** [comment]
Yikes that’s bad. I’ll look into it.

**Comment by iamdoubz** [comment]
Should be fixed thanks to @fruworg and pull #8

**Comment by Thaodan** [comment]
Thanks
